apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: presentacion-pjc
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: presentacion-pjc
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 200
      serviceAccountName: presentacion-sa
      containers:
        - name: presentacion-cont
          image: cdocregdes.pronaca.com/test/test-api-pjc:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 1Gi
      imagePullSecrets:
      - name: registry-private
