kind: Service
apiVersion: v1
metadata:
  name: presentacion-pjc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: presentacion-pjc
  ports:
  - name: http
    port: 80
    targetPort: 8080
